version: '3.4'
services:
    web:
        image: nginx:latest
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
            #- "./nginx/ssl:/etc/ssl"
            - /mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base:rw
        ports:
            - "80:80"
        restart: always
        depends_on:
            - php
    php:
        image: 10xjzheng/php-fpm:latest
        volumes:
            - /mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base:rw
        ports:
            - "9000:9000"
        restart: always
