version: '3.4'
services:
    web:
        image: nginx:latest
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
            #- "./nginx/ssl:/etc/ssl"
            - "/mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base"
        ports:
            - "80:80"  # api http
            - "443:443" # api https
        restart: always
        depends_on:
            - php
    php:
        image: 10xjzheng/swoole:latest
        volumes:
            - "/mnt/d/wamp/www/qmyx-base:/home/web"
        ports:
            - "8888:80"
        command: php /home/web/yii swoole-backend/start 
        restart: always
